<?php

namespace Vipa\ExportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataExportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataExportRepository extends EntityRepository
{
}
